### ISSUE TITLE
Timepix3 component does not work with old data source naming

### ISSUE THREAD

**Issue by bj-s** [European-XFEL/EXtra#252]
The `Timepix3` component does not accept the data sources used with the initial (now old) implementation of the Timepix3 camera.

1) the regular expression used to identify the data source is not accounting for those names
2) the class requires `/DET/` to be part of the source name to identify it as pixelated data

data sources are:
* 'SQS_AQS_CAM/CAM/TIMEPIX3' (control)
* 'SQS_AQS_CAM/CAM/TIMEPIX3:daqEventOutput' (pixelated data)

see e.g. p2873, run 118.

**Comment by philsmt** [comment]
I suspected this would happen, as the current simple code only allows to specify the domain in order to always capture both instrument sources (raw and centroided). In line with other components, It should proably allow entirely arbitrary source names for either.

I take it the number of proposal with this is fairly limited here? Then we can keep the autodetection as is and add an override for explicit source names.

**Comment by bj-s** [comment]
Yes, I agree. An override for explicit source names would be sufficient.
